// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MotionApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// One orientation reading, already reduced to screen axes by the native side.
///
/// The native halves do no filtering. Calibration, latency prediction,
/// smoothing and drift washout all live in Dart.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MotionFrame: Hashable, CustomStringConvertible {
  /// Current pose as a row-major 3x3, columns being screen-right, screen-up
  /// and screen-normal, expressed in the platform's orientation reference
  /// frame. Exactly nine values.
  var screenMatrix: FlutterStandardTypedData
  /// Angular rate about the screen's up axis, rad/s. Drives latency
  /// prediction for the horizontal tilt axis.
  var omegaScreenY: Double
  /// Angular rate about the screen's right axis, rad/s. Drives latency
  /// prediction for the vertical tilt axis.
  var omegaScreenX: Double
  /// Magnitude of the full rotation rate vector, rad/s. Decides whether the
  /// device is still enough for the auto-recenter washout to run.
  var omegaMagnitude: Double
  /// Whether a gyroscope reading backed this frame.
  var hasGyro: Bool
  /// Sensor timestamp in seconds. Only differences are ever used, so the
  /// epoch need not agree across platforms.
  var timestampSeconds: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MotionFrame? {
    let screenMatrix = pigeonVar_list[0] as! FlutterStandardTypedData
    let omegaScreenY = pigeonVar_list[1] as! Double
    let omegaScreenX = pigeonVar_list[2] as! Double
    let omegaMagnitude = pigeonVar_list[3] as! Double
    let hasGyro = pigeonVar_list[4] as! Bool
    let timestampSeconds = pigeonVar_list[5] as! Double

    return MotionFrame(
      screenMatrix: screenMatrix,
      omegaScreenY: omegaScreenY,
      omegaScreenX: omegaScreenX,
      omegaMagnitude: omegaMagnitude,
      hasGyro: hasGyro,
      timestampSeconds: timestampSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      screenMatrix,
      omegaScreenY,
      omegaScreenX,
      omegaMagnitude,
      hasGyro,
      timestampSeconds,
    ]
  }
  static func == (lhs: MotionFrame, rhs: MotionFrame) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MotionApiPigeonInternal.deepEquals(lhs.screenMatrix, rhs.screenMatrix) && MotionApiPigeonInternal.deepEquals(lhs.omegaScreenY, rhs.omegaScreenY) && MotionApiPigeonInternal.deepEquals(lhs.omegaScreenX, rhs.omegaScreenX) && MotionApiPigeonInternal.deepEquals(lhs.omegaMagnitude, rhs.omegaMagnitude) && MotionApiPigeonInternal.deepEquals(lhs.hasGyro, rhs.hasGyro) && MotionApiPigeonInternal.deepEquals(lhs.timestampSeconds, rhs.timestampSeconds)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MotionFrame")
    MotionApiPigeonInternal.deepHash(value: screenMatrix, hasher: &hasher)
    MotionApiPigeonInternal.deepHash(value: omegaScreenY, hasher: &hasher)
    MotionApiPigeonInternal.deepHash(value: omegaScreenX, hasher: &hasher)
    MotionApiPigeonInternal.deepHash(value: omegaMagnitude, hasher: &hasher)
    MotionApiPigeonInternal.deepHash(value: hasGyro, hasher: &hasher)
    MotionApiPigeonInternal.deepHash(value: timestampSeconds, hasher: &hasher)
  }

  public var description: String {
    return "MotionFrame(screenMatrix: \(String(describing: screenMatrix)), omegaScreenY: \(String(describing: omegaScreenY)), omegaScreenX: \(String(describing: omegaScreenX)), omegaMagnitude: \(String(describing: omegaMagnitude)), hasGyro: \(String(describing: hasGyro)), timestampSeconds: \(String(describing: timestampSeconds)))"
  }
}

/// Physical facts about the display and the sensors behind it.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MotionMetrics: Hashable, CustomStringConvertible {
  /// Physical pixels per millimetre, or zero when the platform cannot answer.
  var pixelsPerMillimeter: Double
  /// Whether a usable gyro-backed orientation sensor exists. False on
  /// emulators and on devices with no gyroscope.
  var hasRotationSensor: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MotionMetrics? {
    let pixelsPerMillimeter = pigeonVar_list[0] as! Double
    let hasRotationSensor = pigeonVar_list[1] as! Bool

    return MotionMetrics(
      pixelsPerMillimeter: pixelsPerMillimeter,
      hasRotationSensor: hasRotationSensor
    )
  }
  func toList() -> [Any?] {
    return [
      pixelsPerMillimeter,
      hasRotationSensor,
    ]
  }
  static func == (lhs: MotionMetrics, rhs: MotionMetrics) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MotionApiPigeonInternal.deepEquals(lhs.pixelsPerMillimeter, rhs.pixelsPerMillimeter) && MotionApiPigeonInternal.deepEquals(lhs.hasRotationSensor, rhs.hasRotationSensor)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MotionMetrics")
    MotionApiPigeonInternal.deepHash(value: pixelsPerMillimeter, hasher: &hasher)
    MotionApiPigeonInternal.deepHash(value: hasRotationSensor, hasher: &hasher)
  }

  public var description: String {
    return "MotionMetrics(pixelsPerMillimeter: \(String(describing: pixelsPerMillimeter)), hasRotationSensor: \(String(describing: hasRotationSensor)))"
  }
}

private class MotionApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MotionFrame.fromList(self.readValue() as! [Any?])
    case 130:
      return MotionMetrics.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MotionApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MotionFrame {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? MotionMetrics {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MotionApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MotionApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MotionApiPigeonCodecWriter(data: data)
  }
}

class MotionApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MotionApiPigeonCodec(readerWriter: MotionApiPigeonCodecReaderWriter())
}

var motionApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: MotionApiPigeonCodecReaderWriter());

/// Request and response calls into the native side.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DuoMotionHostApi {
  /// Reads display density and sensor availability once.
  func metrics() throws -> MotionMetrics
  /// Unregisters native sensor listeners.
  func stop() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DuoMotionHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MotionApiPigeonCodec.shared }
  /// Sets up an instance of `DuoMotionHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DuoMotionHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Reads display density and sensor availability once.
    let metricsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.duo_animation.DuoMotionHostApi.metrics\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      metricsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.metrics()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      metricsChannel.setMessageHandler(nil)
    }
    /// Unregisters native sensor listeners.
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.duo_animation.DuoMotionHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        do {
          try api.stop()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// The orientation sample stream.
class StreamMotionStreamHandler: PigeonEventChannelWrapper<MotionFrame> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamMotionStreamHandler) {
    var channelName = "dev.flutter.pigeon.duo_animation.DuoMotionEventApi.streamMotion"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<MotionFrame>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: motionApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
