// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// One orientation reading, already reduced to screen axes by the native side.
///
/// The native halves do no filtering. Calibration, latency prediction,
/// smoothing and drift washout all live in Dart.
class MotionFrame {
  MotionFrame({
    required this.screenMatrix,
    required this.omegaScreenY,
    required this.omegaScreenX,
    required this.omegaMagnitude,
    required this.hasGyro,
    required this.timestampSeconds,
  });

  /// Current pose as a row-major 3x3, columns being screen-right, screen-up
  /// and screen-normal, expressed in the platform's orientation reference
  /// frame. Exactly nine values.
  Float64List screenMatrix;

  /// Angular rate about the screen's up axis, rad/s. Drives latency
  /// prediction for the horizontal tilt axis.
  double omegaScreenY;

  /// Angular rate about the screen's right axis, rad/s. Drives latency
  /// prediction for the vertical tilt axis.
  double omegaScreenX;

  /// Magnitude of the full rotation rate vector, rad/s. Decides whether the
  /// device is still enough for the auto-recenter washout to run.
  double omegaMagnitude;

  /// Whether a gyroscope reading backed this frame.
  bool hasGyro;

  /// Sensor timestamp in seconds. Only differences are ever used, so the
  /// epoch need not agree across platforms.
  double timestampSeconds;

  List<Object?> _toList() {
    return <Object?>[
      screenMatrix,
      omegaScreenY,
      omegaScreenX,
      omegaMagnitude,
      hasGyro,
      timestampSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static MotionFrame decode(Object result) {
    result as List<Object?>;
    return MotionFrame(
      screenMatrix: result[0]! as Float64List,
      omegaScreenY: result[1]! as double,
      omegaScreenX: result[2]! as double,
      omegaMagnitude: result[3]! as double,
      hasGyro: result[4]! as bool,
      timestampSeconds: result[5]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MotionFrame || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(screenMatrix, other.screenMatrix) && _deepEquals(omegaScreenY, other.omegaScreenY) && _deepEquals(omegaScreenX, other.omegaScreenX) && _deepEquals(omegaMagnitude, other.omegaMagnitude) && _deepEquals(hasGyro, other.hasGyro) && _deepEquals(timestampSeconds, other.timestampSeconds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MotionFrame(screenMatrix: $screenMatrix, omegaScreenY: $omegaScreenY, omegaScreenX: $omegaScreenX, omegaMagnitude: $omegaMagnitude, hasGyro: $hasGyro, timestampSeconds: $timestampSeconds)';
  }
}

/// Physical facts about the display and the sensors behind it.
class MotionMetrics {
  MotionMetrics({
    required this.pixelsPerMillimeter,
    required this.hasRotationSensor,
  });

  /// Physical pixels per millimetre, or zero when the platform cannot answer.
  double pixelsPerMillimeter;

  /// Whether a usable gyro-backed orientation sensor exists. False on
  /// emulators and on devices with no gyroscope.
  bool hasRotationSensor;

  List<Object?> _toList() {
    return <Object?>[
      pixelsPerMillimeter,
      hasRotationSensor,
    ];
  }

  Object encode() {
    return _toList();  }

  static MotionMetrics decode(Object result) {
    result as List<Object?>;
    return MotionMetrics(
      pixelsPerMillimeter: result[0]! as double,
      hasRotationSensor: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MotionMetrics || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pixelsPerMillimeter, other.pixelsPerMillimeter) && _deepEquals(hasRotationSensor, other.hasRotationSensor);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MotionMetrics(pixelsPerMillimeter: $pixelsPerMillimeter, hasRotationSensor: $hasRotationSensor)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is MotionFrame) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is MotionMetrics) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return MotionFrame.decode(readValue(buffer)!);
      case 130:
        return MotionMetrics.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

/// Request and response calls into the native side.
class DuoMotionHostApi {
  /// Constructor for [DuoMotionHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DuoMotionHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Reads display density and sensor availability once.
  Future<MotionMetrics> metrics() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.duo_animation.DuoMotionHostApi.metrics$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MotionMetrics;
  }

  /// Unregisters native sensor listeners.
  Future<void> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.duo_animation.DuoMotionHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

/// The orientation sample stream.
/// Orientation frames at roughly the platform's game-sensor rate.
///
/// Returns a broadcast [Stream] of events from the `streamMotion` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<MotionFrame> streamMotion( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamMotionChannel =
      EventChannel('dev.flutter.pigeon.duo_animation.DuoMotionEventApi.streamMotion$instanceName', pigeonMethodCodec);
  return streamMotionChannel.receiveBroadcastStream().map((dynamic event) {
    return event as MotionFrame;
  });
}
    
