// Autogenerated from Pigeon (v28.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.duoanimation.duo_animation

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MotionApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * One orientation reading, already reduced to screen axes by the native side.
 *
 * The native halves do no filtering. Calibration, latency prediction,
 * smoothing and drift washout all live in Dart.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MotionFrame (
  /**
   * Current pose as a row-major 3x3, columns being screen-right, screen-up
   * and screen-normal, expressed in the platform's orientation reference
   * frame. Exactly nine values.
   */
  val screenMatrix: DoubleArray,
  /**
   * Angular rate about the screen's up axis, rad/s. Drives latency
   * prediction for the horizontal tilt axis.
   */
  val omegaScreenY: Double,
  /**
   * Angular rate about the screen's right axis, rad/s. Drives latency
   * prediction for the vertical tilt axis.
   */
  val omegaScreenX: Double,
  /**
   * Magnitude of the full rotation rate vector, rad/s. Decides whether the
   * device is still enough for the auto-recenter washout to run.
   */
  val omegaMagnitude: Double,
  /** Whether a gyroscope reading backed this frame. */
  val hasGyro: Boolean,
  /**
   * Sensor timestamp in seconds. Only differences are ever used, so the
   * epoch need not agree across platforms.
   */
  val timestampSeconds: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MotionFrame {
      val screenMatrix = pigeonVar_list[0] as DoubleArray
      val omegaScreenY = pigeonVar_list[1] as Double
      val omegaScreenX = pigeonVar_list[2] as Double
      val omegaMagnitude = pigeonVar_list[3] as Double
      val hasGyro = pigeonVar_list[4] as Boolean
      val timestampSeconds = pigeonVar_list[5] as Double
      return MotionFrame(screenMatrix, omegaScreenY, omegaScreenX, omegaMagnitude, hasGyro, timestampSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      screenMatrix,
      omegaScreenY,
      omegaScreenX,
      omegaMagnitude,
      hasGyro,
      timestampSeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MotionFrame
    return MotionApiPigeonUtils.deepEquals(this.screenMatrix, other.screenMatrix) && MotionApiPigeonUtils.deepEquals(this.omegaScreenY, other.omegaScreenY) && MotionApiPigeonUtils.deepEquals(this.omegaScreenX, other.omegaScreenX) && MotionApiPigeonUtils.deepEquals(this.omegaMagnitude, other.omegaMagnitude) && MotionApiPigeonUtils.deepEquals(this.hasGyro, other.hasGyro) && MotionApiPigeonUtils.deepEquals(this.timestampSeconds, other.timestampSeconds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MotionApiPigeonUtils.deepHash(this.screenMatrix)
    result = 31 * result + MotionApiPigeonUtils.deepHash(this.omegaScreenY)
    result = 31 * result + MotionApiPigeonUtils.deepHash(this.omegaScreenX)
    result = 31 * result + MotionApiPigeonUtils.deepHash(this.omegaMagnitude)
    result = 31 * result + MotionApiPigeonUtils.deepHash(this.hasGyro)
    result = 31 * result + MotionApiPigeonUtils.deepHash(this.timestampSeconds)
    return result
  }
  override fun toString(): String {
    return "MotionFrame(screenMatrix=${screenMatrix.contentToString()}, omegaScreenY=$omegaScreenY, omegaScreenX=$omegaScreenX, omegaMagnitude=$omegaMagnitude, hasGyro=$hasGyro, timestampSeconds=$timestampSeconds)"
  }
}

/**
 * Physical facts about the display and the sensors behind it.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MotionMetrics (
  /** Physical pixels per millimetre, or zero when the platform cannot answer. */
  val pixelsPerMillimeter: Double,
  /**
   * Whether a usable gyro-backed orientation sensor exists. False on
   * emulators and on devices with no gyroscope.
   */
  val hasRotationSensor: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MotionMetrics {
      val pixelsPerMillimeter = pigeonVar_list[0] as Double
      val hasRotationSensor = pigeonVar_list[1] as Boolean
      return MotionMetrics(pixelsPerMillimeter, hasRotationSensor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pixelsPerMillimeter,
      hasRotationSensor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MotionMetrics
    return MotionApiPigeonUtils.deepEquals(this.pixelsPerMillimeter, other.pixelsPerMillimeter) && MotionApiPigeonUtils.deepEquals(this.hasRotationSensor, other.hasRotationSensor)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MotionApiPigeonUtils.deepHash(this.pixelsPerMillimeter)
    result = 31 * result + MotionApiPigeonUtils.deepHash(this.hasRotationSensor)
    return result
  }
  override fun toString(): String {
    return "MotionMetrics(pixelsPerMillimeter=$pixelsPerMillimeter, hasRotationSensor=$hasRotationSensor)"
  }
}
private open class MotionApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MotionFrame.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MotionMetrics.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MotionFrame -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is MotionMetrics -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MotionApiPigeonMethodCodec = StandardMethodCodec(MotionApiPigeonCodec())

/**
 * Request and response calls into the native side.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface DuoMotionHostApi {
  /** Reads display density and sensor availability once. */
  fun metrics(): MotionMetrics
  /** Unregisters native sensor listeners. */
  fun stop()

  companion object {
    /** The codec used by DuoMotionHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MotionApiPigeonCodec()
    }
    /** Sets up an instance of `DuoMotionHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DuoMotionHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.duo_animation.DuoMotionHostApi.metrics$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.metrics())
            } catch (exception: Throwable) {
              MotionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.duo_animation.DuoMotionHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stop()
              listOf(null)
            } catch (exception: Throwable) {
              MotionApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MotionApiPigeonStreamHandler<T>(
    val wrapper: MotionApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MotionApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/** The orientation sample stream. */
abstract class StreamMotionStreamHandler : MotionApiPigeonEventChannelWrapper<MotionFrame> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamMotionStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.duo_animation.DuoMotionEventApi.streamMotion"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MotionApiPigeonStreamHandler<MotionFrame>(streamHandler)
      EventChannel(messenger, channelName, MotionApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from MotionApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<MotionFrame>) {}

override fun onCancel(p0: Any?) {}
}
      
